## This configuration was generated by terraform-provider-oci

resource oci_core_drg_attachment export_drgattachment20191121142607 {
  display_name   = "drgattachment20191121142607"
  drg_id         = "${oci_core_drg.export_drg-gw01.id}"
  route_table_id = "${oci_core_route_table.export_rt-azure02.id}"
  vcn_id         = "${oci_core_vcn.export_gw-vcn-01.id}"
}

resource oci_core_drg export_drg-gw01 {
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  display_name  = "drg-gw01"
  freeform_tags = {}
}

resource oci_core_service_gateway export_sg_gw01 {
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  display_name  = "sg_gw01"
  freeform_tags = {}

  route_table_id = "${oci_core_route_table.export_rt-azure01.id}"

  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }

  vcn_id = "${oci_core_vcn.export_gw-vcn-01.id}"
}

resource oci_core_vcn export_gw-vcn-01 {
  cidr_block     = "10.1.0.0/16"
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  display_name  = "gw-vcn-01"
  dns_label     = "gwvcn01"
  freeform_tags = {}

  #ipv6cidr_block = <<Optional value not found in discovery>>
  #is_ipv6enabled = <<Optional value not found in discovery>>
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-gw-vcn-01 {
  defined_tags = {}

  display_name  = "Default DHCP Options for gw-vcn-01"
  freeform_tags = {}

  manage_default_resource_id = "${oci_core_vcn.export_gw-vcn-01.default_dhcp_options_id}"

  options {
    custom_dns_servers = []

    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }

  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "gwvcn01.oraclevcn.com",
    ]

    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_internet_gateway export_ig-gw01 {
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  display_name  = "ig-gw01"
  enabled       = "true"
  freeform_tags = {}

  vcn_id = "${oci_core_vcn.export_gw-vcn-01.id}"
}

resource oci_core_route_table export_rt-oci-azure {
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  display_name  = "rt-oci-azure"
  freeform_tags = {}

  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "${oci_core_internet_gateway.export_ig-gw01.id}"
  }

  route_rules {
    destination       = "10.77.0.0/16"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "${oci_core_drg.export_drg-gw01.id}"
  }

  vcn_id = "${oci_core_vcn.export_gw-vcn-01.id}"
}

resource oci_core_route_table export_rt-azure02 {
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  display_name  = "rt-azure02"
  freeform_tags = {}

  route_rules {
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = "${oci_core_service_gateway.export_sg_gw01.id}"
  }

  vcn_id = "${oci_core_vcn.export_gw-vcn-01.id}"
}

resource oci_core_route_table export_rt-azure01 {
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  display_name  = "rt-azure01"
  freeform_tags = {}

  route_rules {
    destination       = "10.77.0.0/16"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "${oci_core_drg.export_drg-gw01.id}"
  }

  vcn_id = "${oci_core_vcn.export_gw-vcn-01.id}"
}

resource oci_core_default_route_table export_Default-Route-Table-for-gw-vcn-01 {
  defined_tags = {}

  display_name  = "Default Route Table for gw-vcn-01"
  freeform_tags = {}

  manage_default_resource_id = "${oci_core_vcn.export_gw-vcn-01.default_route_table_id}"

  route_rules {
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = "${oci_core_internet_gateway.export_ig-gw01.id}"
  }
}

resource oci_core_security_list export_public {
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  display_name  = "public"
  freeform_tags = {}

  ingress_security_rules {
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"

    tcp_options {
      max = "22"
      min = "22"

      #source_port_range = <<Optional value not found in discovery>>
    }

    #udp_options = <<Optional value not found in discovery>>
  }

  ingress_security_rules {
    icmp_options {
      code = "8"
      type = "8"
    }

    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"

    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }

  vcn_id = "${oci_core_vcn.export_gw-vcn-01.id}"
}

resource oci_core_security_list export_sl-gw-oci-azure {
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  display_name = "sl-gw-oci-azure"

  egress_security_rules {
    destination      = "10.77.0.0/16"
    destination_type = "CIDR_BLOCK"

    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "6"
    stateless = "true"

    tcp_options {
      max = "443"
      min = "443"

      #source_port_range = <<Optional value not found in discovery>>
    }

    #udp_options = <<Optional value not found in discovery>>
  }

  egress_security_rules {
    destination      = "10.77.0.0/16"
    destination_type = "CIDR_BLOCK"

    icmp_options {
      code = "8"
      type = "8"
    }

    protocol  = "1"
    stateless = "false"

    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }

  freeform_tags = {}

  ingress_security_rules {
    icmp_options {
      code = "8"
      type = "8"
    }

    protocol    = "1"
    source      = "10.77.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"

    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }

  ingress_security_rules {
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.77.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"

    tcp_options {
      max = "22"
      min = "22"

      #source_port_range = <<Optional value not found in discovery>>
    }

    #udp_options = <<Optional value not found in discovery>>
  }

  ingress_security_rules {
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.77.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"

    tcp_options {
      max = "1522"
      min = "1521"

      #source_port_range = <<Optional value not found in discovery>>
    }

    #udp_options = <<Optional value not found in discovery>>
  }

  vcn_id = "${oci_core_vcn.export_gw-vcn-01.id}"
}

resource oci_core_default_security_list export_Default-Security-List-for-gw-vcn-01 {
  defined_tags = {}

  display_name = "Default Security List for gw-vcn-01"

  egress_security_rules {
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"

    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"

    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }

  freeform_tags = {}

  ingress_security_rules {
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"

    tcp_options {
      max = "22"
      min = "22"

      #source_port_range = <<Optional value not found in discovery>>
    }

    #udp_options = <<Optional value not found in discovery>>
  }

  ingress_security_rules {
    icmp_options {
      code = "4"
      type = "3"
    }

    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"

    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }

  ingress_security_rules {
    icmp_options {
      code = "-1"
      type = "3"
    }

    protocol    = "1"
    source      = "10.1.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"

    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }

  manage_default_resource_id = "${oci_core_vcn.export_gw-vcn-01.default_security_list_id}"
}

resource oci_core_subnet export_sn-gw-vcn-01-01 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.1.1.0/24"
  compartment_id = "${var.compartment_ocid}"
  defined_tags   = {}

  dhcp_options_id = "${oci_core_vcn.export_gw-vcn-01.default_dhcp_options_id}"
  display_name    = "sn-gw-vcn-01-01"
  dns_label       = "sngwvcn0101"
  freeform_tags   = {}

  #ipv6cidr_block = <<Optional value not found in discovery>>
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = "${oci_core_route_table.export_rt-oci-azure.id}"

  security_list_ids = [
    "${oci_core_security_list.export_public.id}",
    "${oci_core_security_list.export_sl-gw-oci-azure.id}",
    "${oci_core_vcn.export_gw-vcn-01.default_security_list_id}",
  ]

  vcn_id = "${oci_core_vcn.export_gw-vcn-01.id}"
}


resource oci_core_virtual_circuit export_fc-gw01 {
  bandwidth_shape_name = "1 Gbps"
  compartment_id       = "${var.compartment_ocid}"

  cross_connect_mappings {    
    customer_bgp_peering_ip = "10.0.0.22/30"
    oracle_bgp_peering_ip = "10.0.0.21/30"  
  }

  cross_connect_mappings {    
    customer_bgp_peering_ip = "10.0.0.26/30"
    oracle_bgp_peering_ip = "10.0.0.25/30"  
  }

  #customer_asn = "12076"
 

  display_name  = "fc-gw01"
  

  gateway_id                = "${oci_core_drg.export_drg-gw01.id}"
  provider_service_id       = "ocid1.providerservice.oc1.iad.aaaaaaaamdyta753fb6tshj3p2g5zezjwfoki5l46jcaaikxt3hszboiag4q"
  provider_service_key_name = "b36ee1c0-ff49-4126-b6e6-40b0c8d98e7a"

  #region = <<Optional value not found in discovery>>
  type = "PRIVATE"
}
