## This configuration was generated by terraform-provider-oci

resource oci_database_db_system export_dbvm_gw01 {
  availability_domain    = "${data.oci_identity_availability_domain.export_Wude-US-ASHBURN-AD-1.name}"
  backup_network_nsg_ids = []

  #backup_subnet_id = <<Optional value not found in discovery>>
  #cluster_name = <<Optional value not found in discovery>>
  compartment_id = "${var.compartment_ocid}"

  cpu_core_count          = "1"
  data_storage_percentage = "80"
  data_storage_size_in_gb = "256"
  database_edition        = "ENTERPRISE_EDITION"

  db_home {
    database {
      admin_password = "TEst#-1234"
      #backup_id = <<Optional value not found in discovery>>
      #backup_tde_password = <<Optional value not found in discovery>>
      character_set = "AL32UTF8"

      db_backup_config {
        auto_backup_enabled = "false"
        auto_backup_window  = ""

        #recovery_window_in_days = <<Optional value not found in discovery>>
      }

      db_name      = "db19vm1"
      db_workload  = "OLTP"
      defined_tags = {}

      freeform_tags = {}

      ncharacter_set = "AL16UTF16"
      pdb_name       = "pdb19vm1"
    }

    db_version   = "19.0.0.0"
    display_name = "dbhome20191212"
  }

  db_system_options {
    storage_management = "ASM"
  }

  defined_tags = {}

  disk_redundancy = "HIGH"
  display_name    = "gw_db19vm1"
 # domain          = "sngwvcn0101.gwvcn01.oraclevcn.com"

 # fault_domains = [
 #   "FAULT-DOMAIN-1",
 # ]

  freeform_tags = {}

  hostname      = "db19vm1"
  license_model = "LICENSE_INCLUDED"
  node_count    = "1"
  nsg_ids       = []

  shape  = "VM.Standard2.1"
  source = "NONE"

  #sparse_diskgroup = <<Optional value not found in discovery>>
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCihjbOdtpdxTVjIqqH/vrTZAC7tZYP6A8wpr6EeZK1uwcNNUopaYJeGmhFGXehY/4NbQGGjXIdnVpqtY4CLm3kRrTBOOvtF60eTCysYIT5LhSbq5OP0dIVpxrZmZGSstEnoWB8fhi7KexNpQgDdsfjFl+Rjd9DCCAo3dlOFkkLBYtzEdIOcsm1CAD0s32FSQrD2/oul9vVjj/wAvEQ4qzgR6xIOx3HgJTbWDP4kss8K6wHp+7kd5WagdWebTfMfDHXOo1lh9dF3tHaFLuH31eH7ZbqpqzgrZu39fHmhhsnBIX/yXz9i954xXHEV9/OUOwFEse30LSAXnH+5PWvqCUR terraform",
  ]

  subnet_id = "${oci_core_subnet.export_sn-gw-vcn-01-01.id}"
  time_zone = "UTC"
}

resource oci_database_autonomous_database export_adwgw01 {
  admin_password = "Oracle@123456"
  #autonomous_container_database_id = <<Optional value not found in discovery>>
  #clone_type = <<Optional value not found in discovery>>
  compartment_id = "${var.compartment_ocid}"

  cpu_core_count           = "1"
  data_safe_status         = "NOT_REGISTERED"
  data_storage_size_in_tbs = "1"
  db_name                  = "gwadw01"
  db_workload              = "DW"
  defined_tags             = {}

  display_name  = "gwadw01"
  freeform_tags = {}

  is_auto_scaling_enabled = "false"
  is_dedicated            = "false"
  is_free_tier            = "false"

  #is_preview_version_with_service_terms_accepted = <<Optional value not found in discovery>>
  license_model = "LICENSE_INCLUDED"

  #source = <<Optional value not found in discovery>>
  #source_id = <<Optional value not found in discovery>>
  whitelisted_ips = []
}
